# heroku-postgres-c4637405 :: gold
development:
  adapter: postgresql
  encoding: unicode
  database: dacp2989dv7omm
  pool: 5
  host: ec2-23-23-81-221.compute-1.amazonaws.com
  username: utfiogalcrchax
  password: Ue2jBFU4ggO-G_SsNZuNHqRTuT

# heroku-postgres-8f0bd529 :: silver
test:
  adapter: postgresql
  encoding: unicode
  database: ddnnld6juoehqd
  pool: 5
  host: ec2-23-23-126-39.compute-1.amazonaws.com
  username: yogdbjhbirakin
  password: WJucXE0EAriLPc0HWf96w7tyZd

# polar-badlands-9747 - database
production:
  adapter: postgresql
  encoding: unicode
  database: d5rs7ch5g9q97m
  pool: 5
  host: ec2-23-23-126-39.compute-1.amazonaws.com
  username: prnqwjjexjpbiy
  password: lTBO-kyTepZ5SXESykwhzHSG44