development:
  adapter: postgresql
  encoding: unicode
  database: pup-share-dev
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pup-share-test
  pool: 5
  host: localhost
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: d5rs7ch5g9q97m
  pool: 5
  host: ec2-23-23-126-39.compute-1.amazonaws.com
  username: prnqwjjexjpbiy
  password: lTBO-kyTepZ5SXESykwhzHSG44